//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты
    {
        public int Номер_зачетной_книжки { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string ФИО
        {
            get
            {
                return $"{Фамилия} {Имя} {Отчество}";
            }
        }
        public string Живет_ли_студент_в_общежитии { get; set; }
        public Nullable<int> Индекс_группы { get; set; }
        public string РПМ { get; set; }
        public string ТРиЗБД { get; set; }
        public string ОКФСК { get; set; }
        public string П_и_ТПТ { get; set; }
        public string СС_и_ТД { get; set; }
    }
}
